name = "CurrencyAmounts"
uuid = "35f9db7c-caf0-4b8b-9aa8-b55447bc07d3"
authors = ["Benjamin Lungwitz <benj.lung@googlemail.com> and contributors"]
version = "0.1.2"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
